export const employees = [
    {
        name: 'Admin PPEF',
        email: 'admn.ppef@gmail.com',
        position: 'CEO',
        role: 'owner',
        roleLabel: 'Owner',
    },
    {
        name: 'Employee PPEF',
        email: 'employee.ppef@gmail.com',
        position: 'Front End Developer',
        role: 'employee',
        roleLabel: 'Employee',
    },
    {
        name: 'Tim Allen',
        email: 'tim@paypay.com',
        position: 'CTO',
        role: 'manager',
        roleLabel: 'Manager',
    },
    {
        name: 'Denzel Washington',
        email: 'denzel@paypay.com',
        position: 'CFO',
        role: 'manager',
        roleLabel: 'Manager',
    },
    {
        name: 'Robin Williams',
        email: 'robin@paypay.com',
        position: 'CMO',
        role: 'manager',
        roleLabel: 'Manager',
    },
    {
        name: 'Reese Witherspoon',
        email: 'reese@paypay.com',
        position: 'Project Manager',
        role: 'employee',
        roleLabel: 'Employee',
    },
    {
        name: 'Scarlet Johansson',
        email: 'scarlet@paypay.com',
        position: 'Front End Engineer',
        role: 'employee',
        roleLabel: 'Employee',
    },
    {
        name: 'Will Ferrell',
        email: 'will@paypay.com',
        position: 'Back End Engineer',
        role: 'employee',
        roleLabel: 'Employee',
    },
    {
        name: 'Helen Hunt',
        email: 'helen@paypay.com',
        position: 'Project Manager',
        role: 'employee',
        roleLabel: 'Employee',
    },
    {
        name: 'Ryan Reynolds',
        email: 'ryan@paypay.com',
        position: 'Dev Ops',
        role: 'employee',
        roleLabel: 'Employee',
    },
];
